### ISSUE TITLE
Parse bug caused by invalid semantic version

### ISSUE THREAD

**Issue by CtrlC-Root** [mschmieder/python-kacl#9]
If you look at lines 106 and 107 in `document.py` it appears `start_pos` and `end_pos` are being used before they are assigned leading to the following error:

```
Unexpected error occured. Make sure your file is a valid Mardown file.
Traceback (most recent call last):                                                    
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/kacl/kacl_cli.py", line 313, in start
    cli(obj={})                        
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)                                                 
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                  
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/core.py", line 610, in invoke                                                 
    return callback(*args, **kwargs)                                                  
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/click-7.1.2-py3.8.egg/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/kacl/kacl_cli.py", line 145, in verify
    valid = kacl_changelog.is_valid()                                                 
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/kacl/document.py", line 222, in is_valid
    validation_results = self.validate()                                              
  File "/home/alex/.virtualenvs/mk-eva/lib/python3.8/site-packages/kacl/document.py", line 106, in validate
    start_pos
UnboundLocalError: local variable 'start_pos' referenced before assignment
```

This was caused by a `CHANGELOG.md` file in a private repository which I can't share but given the location of the bug I don't think it should be too hard to reproduce it. If you can't reproduce it let me know and I will try to extract a minimal subset of the `CHANGELOG.md` that causes the issue.

* https://github.com/mschmieder/python-kacl/blob/master/kacl/document.py#L106

**Comment by mschmieder** [comment]
Hi Alexandru,

this is definitely a bug. The statements actually don't make sense. I'll fix it with the next version.

Thanks for reporting

**Comment by mschmieder** [comment]
Fixed with latest commit on develop
